apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
  namespace: webapp
  labels:
    app: webapp
    service: api
data:
  # Configuration values can be set as key-value properties
  flyway_url: jdbc:postgresql://host.docker.internal:5432/app
  app_hostname: localhost
  app_port: "3000"
  app_db: app
  app_dbhost: host.docker.internal
  app_dbport: "5432"
