apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: webapp
    service: api
spec:
  type: LoadBalancer
  selector:
    app: webapp
    service: api
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
