# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [master]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    environment: ${{ vars.ENVIRONMENT }}
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
      - name: "Create .env file"
        run: |
          touch .env
          echo HOSTNAME=${{ vars.HOSTNAME }} >> .env
          echo PORT=${{ vars.PORT }} >> .env
          echo DATABASE=${{ vars.DATABASE }} >> .env
          echo DBUSER=${{ vars.DBUSER }} >> .env
          echo DBPASSWORD=${{ secrets.DBPASSWORD }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run test
